### ISSUE TITLE
Refactor !commands to use the Telegram command API

### ISSUE THREAD

**Issue by hluaces** [oscarmlage/bofhers#32]
As of now, the bot's is parsing every received text message in order to determine if they are a command or not.

Is this by design? Telegram's [commands api](https://core.telegram.org/bots#commands) allows the bot to receive commands without having to parse any incoming text. It could also allow it to not depend on having to listen too all messages if at some point in the future privacy reasons force us to reevaluate https://github.com/oscarmlage/bofhers/issues/12

It's also helpful because it provides autocompletion, descriptions and prevents us from having to worry about parsing text, which might up bringing more issues.

I want to add category support for `!addquote` and `!quote` and I could benefit from the command API if this is not a design choice.

**Comment by hluaces** [comment]
pinging @oscarmlage

**Comment by oscarmlage** [comment]
Yep, I've thought about that at the beginning: just parse every msg vs telegram commands. One of the purposes of the bot (at the very beginning) was to be able to read all the messages (that's why they're being saved) and offer a kind of periodic "channel summary". I mean something like:

- Top of people talking
- Tagcloud
- Hot topics
- Commonly said words...

But you know, after all this time I had no time to summarize and people is most likely more happy with quotes feature than the other stuff so in the end we can discuss and get rid about the other features in order to have a more structured code (and, of course, privacy reasons, they are always worrying me).

**Comment by hluaces** [comment]
We can have both worlds if we want to:

1. Telegram commands so that we can benefit from the API, parsing and all the related goodies.
2. Channel data saving to create topics and clouds (which properly executed might be useful).

I think we can keep both. Later on, if needed, the "channel reading" can easily be turned off we we have the commands using the respective API.

**Comment by hluaces** [comment]
If that's OK with you I can prepare a PR so that the commands are moved to the API and the rest is kept in the same way (that is: saving messages as they are being saved now). I'd also add some deprecation notices on the `!` commands so that users are asked to move to the `/` command form.

**Comment by oscarmlage** [comment]
> If that's OK with you I can prepare a PR so that the commands are moved to the API and the rest is kept in the same way (that is: saving messages as they are being saved now). I'd also add some deprecation notices on the `!` commands so that users are asked to move to the `/` command form.

Sure! it's perfectly fine.
